# lesson3.2
Программа запрашивает у пользователя ввести целое число, 
а затем пытается преобразовать введенное значение в целочисленный тип. 
Использует блок try-except, чтобы корректно обработать возможные исключения, 
которые могут возникнуть в этом процессе, включая ValueError и TypeError. 
В случае ValueError выведи сообщение "Невозможно преобразовать введенное значение 
в целое число". 
Для TypeError выведи "Введено значение неподходящего типа". 
В обоих случаях программа  просит пользователя попробовать ввести число еще раз.